In [ ]:
#Scikit Learn Library 

Scikit-learn (Sklearn) is the most useful and robust library for machine learning in Python. It provides a selection of efficient tools for machine learning and statistical modeling including classification, regression, clustering and dimensionality reduction via a consistence interface in Python. This library, which is largely written in Python, is built upon NumPy, SciPy and Matplotlib.

In [ ]:
#Import the relevant libraries and read the dataset

In [4]:
import numpy as np

import matplotlib as plt

from sklearn import datasets #various toy datasets 

from sklearn import metrics #Check accuracy of model 

from sklearn.linear_model import LogisticRegression #various supervised and unsupervised learning algorithms

Dataset Loading 

In [5]:
iris = datasets.load_iris()

**Features**− The variables of data are called its features. They are also known as predictors, inputs or attributes.

**Feature matrix** − It is the collection of features, in case there are more than one.

**Feature Names** − It is the list of all the names of the features.

**Response** − It is the output variable that basically depends upon the feature variables. They are also known as target, label or output.

**Response Vector** − It is used to represent response column. Generally, we have just one response column.

**Target Names**− It represent the possible values taken by a response vector.

In [6]:
X = iris.data
y= iris.target

feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


To check the accuracy of our model, we can split the dataset into two pieces-a training set and a testing set. Use the training set to train the model and testing set to test the model. After that, we can evaluate how well our model did.

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size = 0.4, random_state=1
)

**Exercise:** Perform the above steps on any other dataset available in Sklearn library.

In [9]:
import numpy as np
import matplotlib as plt
from sklearn import datasets #various toy datasets 
from sklearn import metrics #Check accuracy of model 
from sklearn.linear_model import LogisticRegression #various supervised and unsupervised learning algorithms

In [12]:
wine = datasets.load_wine()

In [14]:
X=wine.data
Y=wine.target

feature_names = wine.feature_names
target_names = wine.target_names
print("Feature Names : ",feature_names)
print("target Names: ",target_names)
print("First 5 rows of X : \n",X[:5])

Feature Names :  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
target Names:  ['class_0' 'class_1' 'class_2']
First 5 rows of X : 
 [[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]


In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
   X, Y, test_size = 0.4, random_state=1
)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(106, 13)
(72, 13)
(106,)
(72,)
