**Machine Learning Lab#4 - Implement Linear Regression Algorithm on the given dataset**

In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [ ]:
# Inputs (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float64')

In [ ]:
# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [ ]:
# Convert inputs and targets to tensors
x_inputs = torch.from_numpy(inputs)
x_targets = torch.from_numpy(targets)
print(x_inputs)
print(x_targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]], dtype=torch.float64)
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


Linear Regression Model (from scratch)

In [ ]:
# Weights and biases
print(x_inputs.shape[1])
print(x_targets.shape[1])
x_weights = torch.randn(x_inputs.shape[1],x_targets.shape[1],dtype=torch.float64, requires_grad=True )
x_biases = torch.randn(x_inputs.shape[0],x_targets.shape[1], dtype=torch.float64, requires_grad=True)
print(x_weights)
print(x_biases)

3
1
tensor([[0.1092],
        [0.5264],
        [0.1990]], dtype=torch.float64, requires_grad=True)
tensor([[ 1.2466],
        [-0.1265],
        [-0.2498],
        [-0.2106],
        [ 0.3530]], dtype=torch.float64, requires_grad=True)


In [ ]:
# Define the model
model = torch.matmul(x_inputs,x_weights)
model = torch.add(model,x_biases)
model

tensor([[53.0411],
        [68.8662],
        [91.3247],
        [40.9238],
        [72.3484]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [ ]:
# Generate predictions
#Compare with targets
diff = torch.subtract(model,x_targets)
torch.square_(diff)
#MSE loss
loss  = torch.sum(diff)/len(diff)
loss

tensor(443.9072, dtype=torch.float64, grad_fn=<DivBackward0>)

In [ ]:
loss.backward(retain_graph=True)

In [ ]:
print(x_weights.grad)
print(x_biases.grad)

tensor([[-1565.0628],
        [-2841.3355],
        [-1581.7571]], dtype=torch.float64)
tensor([[ -1.1836],
        [ -4.8535],
        [-11.0701],
        [  7.5695],
        [-12.2606]], dtype=torch.float64)
